# Generated by Django 3.0.5 on 2020-04-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtiauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='tag_group_id',
        ),
        migrations.RemoveField(
            model_name='user_tags',
            name='tag_id',
        ),
        migrations.RemoveField(
            model_name='user_tags',
            name='user_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='creator_id',
            new_name='creator',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tag_category_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FilePathField(blank=True, null=True, path='avatar/'),
        ),
        migrations.DeleteModel(
            name='Tag_groups',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
        migrations.DeleteModel(
            name='User_tags',
        ),
    ]
